[launcher]
version = 1.2.1
description = Ingest Anthropic Claude Enterprise compliance audit, usage, cost, and spend-limit data into Splunk with security, governance, and analytics dashboards.
author = Manan Grover

[id]
version = 1.2.1
name = TA-anthropic_claude_enterprise

[install]
build = 1784839306
is_configured = false
state = enabled

[package]
id = TA-anthropic_claude_enterprise
check_for_updates = false

[ui]
label = Anthropic Claude Enterprise Add-on
supported_themes = light, dark
is_visible = true

[triggers]
reload.ta-anthropic_claude_enterprise_settings = simple
reload.ta-anthropic_claude_enterprise_account = simple
