[compliance_activities]
python.version = python3
python.required = 3.13
script = compliance_activities.py

[compliance_directory]
python.version = python3
python.required = 3.13
script = compliance_directory.py

[compliance_content]
python.version = python3
python.required = 3.13
script = compliance_content.py

[analytics_reports]
python.version = python3
python.required = 3.13
script = analytics_reports.py
