[admin:TA-anthropic_claude_enterprise_configuration]
match = /
members = TA-anthropic_claude_enterprise_account, TA-anthropic_claude_enterprise_settings

[admin:TA-anthropic_claude_enterprise_inputs]
match = /
members = TA-anthropic_claude_enterprise_analytics_reports, TA-anthropic_claude_enterprise_compliance_activities, TA-anthropic_claude_enterprise_compliance_content, TA-anthropic_claude_enterprise_compliance_directory

[admin_external:TA-anthropic_claude_enterprise_account]
handlertype = python
python.version = python3
python.required = 3.13
handlerfile = TA-anthropic_claude_enterprise_rh_account.py
handleractions = edit, list, remove, create
handlerpersistentmode = true

[admin_external:TA-anthropic_claude_enterprise_settings]
handlertype = python
python.version = python3
python.required = 3.13
handlerfile = TA-anthropic_claude_enterprise_rh_settings.py
handleractions = edit, list
handlerpersistentmode = true

[admin_external:TA-anthropic_claude_enterprise_compliance_activities]
handlertype = python
python.version = python3
python.required = 3.13
handlerfile = TA-anthropic_claude_enterprise_rh_compliance_activities.py
handleractions = edit, list, remove, create
handlerpersistentmode = true

[admin_external:TA-anthropic_claude_enterprise_compliance_directory]
handlertype = python
python.version = python3
python.required = 3.13
handlerfile = TA-anthropic_claude_enterprise_rh_compliance_directory.py
handleractions = edit, list, remove, create
handlerpersistentmode = true

[admin_external:TA-anthropic_claude_enterprise_compliance_content]
handlertype = python
python.version = python3
python.required = 3.13
handlerfile = TA-anthropic_claude_enterprise_rh_compliance_content.py
handleractions = edit, list, remove, create
handlerpersistentmode = true

[admin_external:TA-anthropic_claude_enterprise_analytics_reports]
handlertype = python
python.version = python3
python.required = 3.13
handlerfile = TA-anthropic_claude_enterprise_rh_analytics_reports.py
handleractions = edit, list, remove, create
handlerpersistentmode = true
