[eventtype=anthropic_claude_auth_events]
authentication = enabled
audit = enabled

[eventtype=anthropic_claude_change_events]
change = enabled
audit = enabled

[eventtype=anthropic_claude_file_events]
audit = enabled

[eventtype=anthropic_claude_usage_events]
audit = enabled
