[expose:TA-anthropic_claude_enterprise_account]
pattern = TA-anthropic_claude_enterprise_account
methods = POST, GET

[expose:TA-anthropic_claude_enterprise_account_specified]
pattern = TA-anthropic_claude_enterprise_account/*
methods = POST, GET, DELETE

[expose:TA-anthropic_claude_enterprise_settings]
pattern = TA-anthropic_claude_enterprise_settings
methods = POST, GET

[expose:TA-anthropic_claude_enterprise_settings_specified]
pattern = TA-anthropic_claude_enterprise_settings/*
methods = POST, GET, DELETE

[expose:TA-anthropic_claude_enterprise_compliance_activities]
pattern = TA-anthropic_claude_enterprise_compliance_activities
methods = POST, GET

[expose:TA-anthropic_claude_enterprise_compliance_activities_specified]
pattern = TA-anthropic_claude_enterprise_compliance_activities/*
methods = POST, GET, DELETE

[expose:TA-anthropic_claude_enterprise_compliance_directory]
pattern = TA-anthropic_claude_enterprise_compliance_directory
methods = POST, GET

[expose:TA-anthropic_claude_enterprise_compliance_directory_specified]
pattern = TA-anthropic_claude_enterprise_compliance_directory/*
methods = POST, GET, DELETE

[expose:TA-anthropic_claude_enterprise_compliance_content]
pattern = TA-anthropic_claude_enterprise_compliance_content
methods = POST, GET

[expose:TA-anthropic_claude_enterprise_compliance_content_specified]
pattern = TA-anthropic_claude_enterprise_compliance_content/*
methods = POST, GET, DELETE

[expose:TA-anthropic_claude_enterprise_analytics_reports]
pattern = TA-anthropic_claude_enterprise_analytics_reports
methods = POST, GET

[expose:TA-anthropic_claude_enterprise_analytics_reports_specified]
pattern = TA-anthropic_claude_enterprise_analytics_reports/*
methods = POST, GET, DELETE

[expose:data/indexes]
pattern = data/indexes
methods = GET
